In [11]:
import pandas as pd
import time
import datetime as dt
from IPython.display import display
import plotly.plotly as py
import numpy as np
import h5py

In [2]:
data_dir = './data/'
evt_name = 'Featurespace_events_output.csv'
auth_name = 'Featurespace_auths_output.csv'
db_name = 'c1_agg.db'

In [79]:
rm_quot_cols = ['mrch_pstl_cd','mrch_nm','trmnl_id','mrch_id','mrch_city_nm']
chunksize = 10
copy_block = 10
j = 0
index_start = 1
###################data source
file_loc = data_dir+auth_name
########################
dtFormat = "%d%b%Y %H:%M:%S.%f"
def getTime(x):
    dtString = "{} {}".format(x.AUTHZN_RQST_PROC_DT,x.AUTHZN_RQST_PROC_TM)
    return dt.datetime.strptime(dtString,dtFormat)

for df in pd.read_csv(file_loc, chunksize=chunksize, iterator=True,encoding='ISO-8859-1'):
    

    t0 = time.time()
    df = df.rename(columns={c: c.replace(' ', '') for c in df.columns}) # Remove spaces from columns

    
    # df[col_id.upper()] = df[col_id.upper()].replace({'\"':''},regex=True)
    # a = df['mrch_nm'.upper()] 
    # print a.dtype
    # a.index = range(len(a))
    # print a[a.str.contains(r".*NATION OF.*",na=False)]
    time_col = 'AUTHZN_RQST_PROC_TM'
    
    
    temp = pd.DatetimeIndex(df['AUTHZN_RQST_PROC_TM'])
    df[col+'_hour'] = temp.hour
    print df[col+'_hour'] 
    df[col+'_minute'] = temp.minute
    df[col+'_second'] = temp.second
    df[col+'_microsecond'] = temp.microsecond
#     df['AUTHZN_RQST_PROC_TM'] = pd.to_datetime(tc,errors='coerce',format='%H:%M:%S.%f')
#     print  df['AUTHZN_RQST_PROC_TM'].date
#     for i in  df['AUTHZN_RQST_PROC_TM']:
#         print type(i)
#         print i
#     temp = pd.DatetimeIndex(df[time_col])


    lista = [item.split(':')[0] for item in df[time_col]]
    display(lista)
    
    df['AUTHZN_RQST_PROC_TM'] = df.apply(lambda x: getTime(x),1)
    # print df['mrch_nm'.upper()]
    df.MRCH_CNTRY_CD = df.MRCH_CNTRY_CD.astype(str)
    df.MRCH_CATG_CD = df.MRCH_CATG_CD.astype(str)
    df.AUTHZN_MSG_TYPE_MODR_CD = df.AUTHZN_MSG_TYPE_MODR_CD.astype(str)
    df.RQST_CARD_SEQ_NUM = df.RQST_CARD_SEQ_NUM.astype(str)
    df.ECMRC_SCURT_CD = df.ECMRC_SCURT_CD.astype(str)
    df.ACQR_BIN_NUM = df.ACQR_BIN_NUM.astype(str)
    date_cols = ['PREV_ADR_CHNG_DT','PREV_PMT_DT','PREV_CARD_RQST_DT','FRD_IND_SWT_DT','AUTHZN_RQST_PROC_DT']
    for col in date_cols:
        tc = df[col]
        tc = pd.to_datetime(tc,errors='coerce',format='%d%b%Y')
        temp = pd.DatetimeIndex(tc)
        components = ['year','month','day','dayofweek']
        df[col+'_data'] = temp.date
        df[col+'_month'] = temp.month
        df[col+'_day'] = temp.day
        df[col+'_dayofweek'] = temp.dayofweek



    break

0    14
1    15
2    22
3    17
4    16
5    12
6    12
7    13
8    10
9     9
Name: AUTHZN_RQST_PROC_DT_hour, dtype: int32


[u'14', u'15', u'22', u'17', u'16', u'12', u'12', u'13', u'10', u'9']

In [69]:
display(df)

acct_id AUTHZN_RQST_PROC_DT AUTHZN_RQST_PROC_TM  AUTHZN_APPRL_CD  \
0  313229902           28MAY2014 2014-05-28 14:30:22             6859   
1  101381867           25AUG2013 2013-08-25 15:32:47            74296   
2    7238423           19AUG2013 2013-08-19 22:17:55            26582   
3   77871292           15FEB2014 2014-02-15 17:11:57            47355   
4  134296672           18DEC2013 2013-12-18 16:25:02            50684   
5  360352196           31DEC2013 2013-12-31 12:24:50            35235   
6  272469810           14DEC2013 2013-12-14 12:49:15            74625   
7   76337635           11OCT2013 2013-10-11 13:35:32            59905   
8  216019144           19MAR2014 2014-03-19 10:03:03            91066   
9   85741865           18NOV2013 2013-11-18 09:35:24            57257   

   AUTHZN_AMT                 MRCH_NM   MRCH_CITY_NM MRCH_PSTL_CD  \
0       14.49               WILKINSON      LANCASTER          NaN   
1        3.99    AOL*UK SecuritySuite    08082349279          NaN   
2        0.69  APPLE ITUNES STORE-GBP     ITUNES.COM          NaN   
3       29.84      WWW.PROBIKEKIT.COM      NORTHWICH          NaN   
4      100.00        ASDA TRAFF PARK2  TRAFFORD PARK      M41 7ZA   
5       22.50                 BHS 013       REDDITCH     B97  4HD   
6        5.10      ONE-SURE INSURANCE  STOKE ON TREN     ST7  1LX   
7       44.94         B & Q WAREHOUSE        SWANSEA          NaN   
8       10.00  SHOPPER DISCOUNTS.CO.U         EYSINS         1262   
9      100.00    TRANSPORT FOR LONDON         LONDON          NaN   

  MRCH_CNTRY_CD           MRCH_ID      ...       PRIOR_MONEY_AVL_AMT  \
0           826  3758125        X      ...                    751.08   
1           826  068636000320937R      ...                   3150.00   
2           442  206996000200925R      ...                    521.25   
3           826  6429369        X      ...                     30.67   
4           826       20-54-58 00      ...                   2872.00   
5           826          09799162      ...                    252.51   
6           826          47177803      ...                   1917.38   
7           826  3412954        X      ...                    997.26   
8           756           8145500      ...                   3279.17   
9           826  1007604        X      ...                   1283.06   

  PRIOR_CASH_AVL_AMT  ACCT_CL_AMT  ACCT_CURR_BAL  PREV_ADR_CHNG_DT  \
0             900.00       1000.0         398.92                 .   
1            3000.00       3000.0           0.00         29SEP2000   
2             700.00        600.0         298.75         23NOV2012   
3            3000.00       3000.0        2969.33         19AUG2013   
4            2942.00       3000.0          58.00         07JAN2010   
5             750.00        750.0         647.49                 .   
6            2576.65       3650.0        1732.62         14NOV2002   
7            1500.00       1500.0         644.19         13FEB2008   
8            4000.00       4000.0         566.86         10JUN2013   
9            1904.13       2600.0        1446.94         05JUL2001   

   PREV_PMT_DT  PREV_PMT_AMT  PREV_CARD_RQST_DT FRD_IND FRD_IND_SWT_DT  
0    14AUG2013        890.17          11MAY2014       N              .  
1    20AUG2013          3.99          02MAR2012       N              .  
2    19AUG2013        100.00          24MAY2013       N              .  
3    07FEB2014         62.79          05FEB2013       N              .  
4    13DEC2013         45.00          03DEC2011       N              .  
5    06DEC2013         14.71          12FEB2013       N              .  
6    01DEC2013        500.00          04OCT2012       N              .  
7    25SEP2013        250.00          02JUN2012       N              .  
8    16MAR2014        189.98          05NOV2011       N              .  
9    28OCT2013         30.00          02FEB2012       N              .  

[10 rows x 48 columns]

In [77]:
py.sign_in('bottydim', 'o1kuyms9zv') 
from plotly.graph_objs import Bar, Scatter, Marker, Layout, Figure
import numpy as np

In [78]:
trace = Scatter(x=np.arange(10),y=np.arange(10))
data = [trace] 
fig = Figure(data=data)
plt_filename ='./test.png'
print plt_filename
py.image.save_as(fig,filename=plt_filename)

./test.png


In [80]:
k

NameError: name 'k' is not defined

In [6]:
x = np.zeros((10,1)).ravel()

In [7]:
x.ravel()

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [91]:
dir_name = '/home/botty/Documents/CCFD/data/models/export/birnn-do3-dle/'
f_name = 'train.hdf5'
# f_name = 'states.hdf5'
file_name = dir_name + f_name
f = h5py.File(file_name)

In [92]:
f.keys()

[u'features', u'labels']

In [93]:
for k in f.keys():
    ds = f.get(k)
    arr = np.array(ds)
    print arr.shape
    print np.count_nonzero(arr)

(6954, 44)
249105
(6954,)
9


In [97]:
np.where(arr==1)

(array([4990, 5001, 5467, 5468, 5469, 5470, 5471, 5472, 5473]),)

In [56]:
list(np.zeros(10))

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [70]:
print 5,'yes',54

5 yes 54


In [78]:
f['/layer_0']

<HDF5 dataset "layer_0": shape (6954, 640), type "<f8">